### ISSUE TITLE
doesn't work on win / virtualbox 5.0.2 / vagrant 1.7.4

### ISSUE THREAD

**Issue by dmitry-saritasa** [William-Yeh/docker-enabled-vagrant#5]
William,

it fails on copying vboxguestadditions, also it fails on custom shell provisioner
**config.vm.provision :shell, path: "init.sh"**

so if I remove shell provisioner and vboxguest plugin - then it's deployed. Maybe the problem is that your solution doesn't use insecure_private_key. 

Any suggestions?

vagrant up

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'williamyeh/centos7-docker'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: dockerhost-fantasyaces
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 27017 => 27017 (adapter 1)
    default: 3306 => 3306 (adapter 1)
    default: 6379 => 6379 (adapter 1)
    default: 8081 => 8081 (adapter 1)
    default: 8080 => 8080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
GuestAdditions versions on your host (5.0.2) and guest (5.0.0) do not match.
CentOS Linux release 7.1.1503 (Core)
Linux     localhost 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: mirror.supremebytes.com
 * extras: mirror.hostduplex.com
 * updates: mirror.hmc.edu
Package kernel-devel-3.10.0-229.11.1.el7.x86_64 already installed and latest version
Package gcc-4.8.3-9.el7.x86_64 already installed and latest version
Package 1:make-3.82-21.el7.x86_64 already installed and latest version
Package 4:perl-5.16.3-285.el7.x86_64 already installed and latest version
Nothing to do
Copy iso file C:\Programming\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
CentOS Linux release 7.1.1503 (Core)
Linux     localhost 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.1.1503 (Core)
Linux     localhost 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
==> default: Checking for guest additions in VM...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'docker' provisioner...
C:/Programming/Vagrant174/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:392:in `await_response_state': CentOS Linux release 7.1.1503 (Core)  (RuntimeError)
Linux     localhost 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
        from C:/Programming/Vagrant174/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:380:in `await_response'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-scp-1.1.2/lib/net/scp/upload.rb:25:in `upload_start_state'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:363:in `block (3 levels) in start_command'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `process'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `each'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:269:in `wait'
        from C:/Programming/Vagrant174/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:279:in `upload!'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/ssh/communicator.rb:271:in `block in upload'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/ssh/communicator.rb:628:in `block in scp_connect'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/ssh/communicator.rb:312:in `connect'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/ssh/communicator.rb:626:in `scp_connect'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/ssh/communicator.rb:265:in `upload'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/installers/base.rb:187:in `upload'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/installers/linux.rb:48:in `install'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/installers/redhat.rb:14:in `install'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/installer.rb:60:in `install'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/machine.rb:93:in `block (2 levels) in
guest_additions_state'
        from C:/Users/Owner/.vagrant.d/gems/gems/micromachine-1.1.0/lib/micromachine.rb:25:in `call'
        from C:/Users/Owner/.vagrant.d/gems/gems/micromachine-1.1.0/lib/micromachine.rb:25:in `block in trigger'
        from C:/Users/Owner/.vagrant.d/gems/gems/micromachine-1.1.0/lib/micromachine.rb:25:in `each'
        from C:/Users/Owner/.vagrant.d/gems/gems/micromachine-1.1.0/lib/micromachine.rb:25:in `trigger'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/machine.rb:36:in `install'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/machine.rb:25:in `run'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-vbguest-0.10.0/lib/vagrant-vbguest/middleware.rb:25:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/wait_for_communicator.rb:71:in
`call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/boot.rb:18:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/sane_defaults.rb:38:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/network.rb:121:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:18:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in
`call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/nfs/action_cleanup.rb:19:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in `handle'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in `block in call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/action/update_all.rb:24:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_check_outdated.rb:23:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/match_mac_address.rb:16:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/import.rb:32:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-triggers-0.5.1/lib/vagrant-triggers/action/trigger.rb:17:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-triggers-0.5.1/lib/vagrant-triggers/action/trigger.rb:17:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/Owner/.vagrant.d/gems/gems/vagrant-triggers-0.5.1/lib/vagrant-triggers/action/trigger.rb:17:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
        from C:/Programming/Vagrant174/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by William-Yeh** [comment]
Thanks for your feedback.

Indeed, the CentOS 7 version of these boxes has some issues with vboxguestadditions. I'm still trying to figure out how to fix it.

PS. Ubuntu and Debian versions are all rewritten in Packer + Bento.

**Comment by William-Yeh** [comment]
Now the `williamyeh/centos7-docker` box has been rewritten in Packer + Bento. I think the vbox guest additions should work fine from now on.

As for the "insecure key" issue, please refer to:
https://github.com/mitchellh/vagrant/issues/5059

You may test with the following files:

**Vagrantfile**:

```
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.ssh.insert_key = false
  config.vm.provision "shell", path: "init.sh"
end
```

**init.sh**:

```
#!/bin/bash

yum -y install tree
```

Test with **`vagrant up`**:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'williamyeh/centos7-docker' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'williamyeh/centos7-docker'
    default: URL: https://atlas.hashicorp.com/williamyeh/centos7-docker
==> default: Adding box 'williamyeh/centos7-docker' (v1.8.1.20150910) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/williamyeh/boxes/centos7-docker/versions/1.8.1.20150910/providers/virtualbox.box
==> default: Successfully added box 'williamyeh/centos7-docker' (v1.8.1.20150910) for 'virtualbox'!
==> default: Importing base box 'williamyeh/centos7-docker'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'williamyeh/centos7-docker' is up to date...
==> default: Setting the name of the VM: z_default_1441877916602_14942
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/william/Documents/AtWork/github/docker/docker-enabled-vagrant/centos7/z
==> default: Running provisioner: shell...
    default: Running: /var/folders/5s/fcj83lkd25g4zdd1bd71kq_m0000gn/T/vagrant-shell20150910-18289-9hinqo.sh
==> default: Loaded plugins: fastestmirror
==> default: Determining fastest mirrors
==> default:  * base: mirror01.idc.hinet.net
==> default:  * extras: mirror01.idc.hinet.net
==> default:  * updates: mirror01.idc.hinet.net
==> default: Resolving Dependencies
==> default: --> Running transaction check
==> default: ---> Package tree.x86_64 0:1.6.0-10.el7 will be installed
==> default: --> Finished Dependency Resolution
==> default:
==> default: Dependencies Resolved
==> default:
==> default: ================================================================================
==> default:  Package        Arch             Version                   Repository      Size
==> default: ================================================================================
==> default: Installing:
==> default:  tree           x86_64           1.6.0-10.el7              base            46 k
==> default:
==> default: Transaction Summary
==> default: ================================================================================
==> default: Install  1 Package
==> default:
==> default: Total download size: 46 k
==> default: Installed size: 87 k
==> default: Downloading packages:
==> default: Running transaction check
==> default: Running transaction test
==> default: Transaction test succeeded
==> default: Running transaction
==> default:   Installing : tree-1.6.0-10.el7.x86_64                                     1/1
==> default:
==> default:   Verifying  : tree-1.6.0-10.el7.x86_64                                     1/1
==> default:
==> default:
==> default: Installed:
==> default:   tree.x86_64 0:1.6.0-10.el7
==> default: Complete!
```
